# Generated by Django 4.2.7 on 2023-11-27 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sushi',
            old_name='idade',
            new_name='chirashi',
        ),
        migrations.RenameField(
            model_name='sushi',
            old_name='name',
            new_name='sushi',
        ),
    ]
